Ref null check
thmsgbrt/react-simple-pull-to-refresh pull request #16
Opened 2021-01-20 13:48 UTC by HamAndRock

Hello,
I came across this bug when navigating through pages. 

When I pull to fetch data and then immidietly navigate to new page (using Next), the code wants to edit styles on previues page and throws Null error on refs.

Feel free to fix it with null null coalescing, I just made a quick PR to point out the problem.

Thanks a lot, Jakub.

2021-01-21 07:48 UTC, thmsgbrt commented
Hi @HamAndRock 
Thanks for your contribution, I'll push your fix asap.
Thomas

2021-01-25 16:30 UTC, HamAndRock commented
I also added check for missing TouchEvent in Mozzila browser

2021-01-25 18:53 UTC, thmsgbrt requested changes
Hi!

I sincerely apologize for the delay. I hope you were not blocked.
Here are few changes and then we are good to go!

2021-01-25 18:53 UTC, thmsgbrt commented on src/components/pull-to-refresh.tsx
>        currentY = e.pageY;
I had a Type issue while checking your branch. Wasn't there any complaint on line 164 for you?
I had to do a type assertion of the "e" to solve it:

` currentY = (e as MouseEvent).pageY;`

2021-01-25 18:53 UTC, thmsgbrt commented on src/components/pull-to-refresh.tsx
> +      if (pullDownRef.current) pullDownRef.current!.style.visibility = 'hidden';
I believe we can remove the non-null assertion operator here:

`if (pullDownRef.current) pullDownRef.current.style.visibility = 'hidden';`

2021-01-25 18:53 UTC, thmsgbrt commented on src/components/pull-to-refresh.tsx
> +      childrenRef.current!.style.overflow = 'visible';
Same, non-null assertion operator can be removed

2021-01-25 18:53 UTC, thmsgbrt commented on src/components/pull-to-refresh.tsx
> +      childrenRef.current!.style.transform = `translate(0px, ${pullDownThreshold}px)`;
Same, non-null assertion operator can be removed

2021-01-25 19:10 UTC, HamAndRock commented
Sorry, was just fixing it in browser I am used to CI to check for compilation errors :D

Should be fixed now.

2021-01-25 19:13 UTC, thmsgbrt commented
Awesome, I'm gonna merge it now and publish a new version!
Thank you for your contribution!

2021-01-25 19:15 UTC, merged